"""State store: schema, connection, and the query helpers the pipeline uses.

DATABASE_URL defaults to ``sqlite:///outbound.db``. Point it at a Postgres URL
(``postgresql+psycopg://...``) and the same schema applies — a thin SQLAlchemy
Core abstraction keeps both backends working. Timestamps are stored as ISO-8601
strings so the same bound parameters work on both dialects.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any, Iterable, Optional

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

from .models import Company, Contact

# --- Schema ------------------------------------------------------------------
# DDL portable across SQLite and Postgres. The only dialect-specific bit is the
# auto-increment primary key on `events`, handled in init_db().

_TABLES_COMMON = [
    """
    CREATE TABLE IF NOT EXISTS companies (
      domain          TEXT PRIMARY KEY,
      name            TEXT,
      industry        TEXT,
      employees       INTEGER,
      revenue_usd     BIGINT,
      technologies    TEXT,
      brief           TEXT NOT NULL,
      status          TEXT NOT NULL,
      drop_reason     TEXT,
      signal_summary  TEXT,
      sourced_at      TIMESTAMP,
      updated_at      TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS contacts (
      email           TEXT PRIMARY KEY,
      company_domain  TEXT NOT NULL REFERENCES companies(domain),
      first_name      TEXT,
      last_name       TEXT,
      title           TEXT,
      seniority       TEXT,
      linkedin        TEXT,
      brief           TEXT NOT NULL,
      cell            TEXT,
      first_line      TEXT,
      subject         TEXT,
      body            TEXT,
      status          TEXT NOT NULL,
      enriched_at     TIMESTAMP,
      loaded_at       TIMESTAMP,
      updated_at      TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS suppression (
      key      TEXT PRIMARY KEY,
      scope    TEXT NOT NULL,
      reason   TEXT,
      added_at TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS runs (
      run_id      TEXT PRIMARY KEY,
      brief       TEXT NOT NULL,
      stage       TEXT NOT NULL,
      status      TEXT NOT NULL,
      counts      TEXT,
      started_at  TIMESTAMP,
      finished_at TIMESTAMP
    )
    """,
]

_EVENTS_SQLITE = """
    CREATE TABLE IF NOT EXISTS events (
      id      INTEGER PRIMARY KEY AUTOINCREMENT,
      email   TEXT,
      type    TEXT NOT NULL,
      payload TEXT,
      at      TIMESTAMP
    )
"""

_EVENTS_POSTGRES = """
    CREATE TABLE IF NOT EXISTS events (
      id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email   TEXT,
      type    TEXT NOT NULL,
      payload TEXT,
      at      TIMESTAMP
    )
"""


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# --- Engine / init -----------------------------------------------------------

def get_engine(database_url: str) -> Engine:
    """Create a SQLAlchemy engine for the given URL (SQLite or Postgres)."""
    kwargs: dict[str, Any] = {"future": True}
    if database_url.startswith("sqlite"):
        # Allow use across threads (validation/research run in thread pools).
        kwargs["connect_args"] = {"check_same_thread": False}
    return create_engine(database_url, **kwargs)


def init_db(engine: Engine) -> None:
    """Create all tables if they do not exist. Idempotent."""
    is_pg = engine.dialect.name == "postgresql"
    with engine.begin() as conn:
        for ddl in _TABLES_COMMON:
            conn.execute(text(ddl))
        conn.execute(text(_EVENTS_POSTGRES if is_pg else _EVENTS_SQLITE))
        # Helpful indexes for the hot lookups.
        conn.execute(text(
            "CREATE INDEX IF NOT EXISTS idx_companies_brief_status "
            "ON companies(brief, status)"
        ))
        conn.execute(text(
            "CREATE INDEX IF NOT EXISTS idx_contacts_brief_status "
            "ON contacts(brief, status)"
        ))


# --- Row <-> dataclass helpers ----------------------------------------------

def _company_from_row(row: Any) -> Company:
    m = row._mapping
    techs = m["technologies"]
    return Company(
        domain=m["domain"],
        name=m["name"] or "",
        industry=m["industry"] or "",
        employees=m["employees"],
        revenue_usd=m["revenue_usd"],
        technologies=json.loads(techs) if techs else [],
        brief=m["brief"],
        status=m["status"],
        drop_reason=m["drop_reason"],
        signal_summary=m["signal_summary"],
    )


def _contact_from_row(row: Any) -> Contact:
    m = row._mapping
    return Contact(
        email=m["email"],
        company_domain=m["company_domain"],
        first_name=m["first_name"] or "",
        last_name=m["last_name"] or "",
        title=m["title"] or "",
        seniority=m["seniority"] or "",
        linkedin=m["linkedin"] or "",
        brief=m["brief"],
        cell=m["cell"],
        first_line=m["first_line"],
        subject=m["subject"],
        body=m["body"],
        status=m["status"],
    )


# --- Database facade ---------------------------------------------------------

class Database:
    """Thin convenience wrapper over a SQLAlchemy engine.

    Methods here are the only seam the pipeline uses, keeping SQL in one place
    and both backends interchangeable.
    """

    def __init__(self, database_url: str):
        self.engine = get_engine(database_url)

    def init(self) -> None:
        init_db(self.engine)

    # -- dedup / existence ----------------------------------------------------

    def company_exists(self, domain: str) -> bool:
        with self.engine.connect() as conn:
            r = conn.execute(
                text("SELECT 1 FROM companies WHERE domain = :d"), {"d": domain}
            ).first()
        return r is not None

    def contact_exists(self, email: str) -> bool:
        with self.engine.connect() as conn:
            r = conn.execute(
                text("SELECT 1 FROM contacts WHERE email = :e"), {"e": email}
            ).first()
        return r is not None

    def is_suppressed(self, key: str) -> bool:
        with self.engine.connect() as conn:
            r = conn.execute(
                text("SELECT 1 FROM suppression WHERE key = :k"), {"k": key}
            ).first()
        return r is not None

    # -- companies ------------------------------------------------------------

    def insert_company(self, c: Company) -> bool:
        """Insert a SOURCED company. Returns False if it already exists
        (single-touch dedup) or is suppressed."""
        if self.company_exists(c.domain) or self.is_suppressed(c.domain):
            return False
        ts = now_iso()
        with self.engine.begin() as conn:
            conn.execute(text(
                """
                INSERT INTO companies
                  (domain, name, industry, employees, revenue_usd, technologies,
                   brief, status, drop_reason, signal_summary, sourced_at, updated_at)
                VALUES
                  (:domain, :name, :industry, :employees, :revenue_usd, :technologies,
                   :brief, :status, :drop_reason, :signal_summary, :ts, :ts)
                """
            ), {
                "domain": c.domain,
                "name": c.name,
                "industry": c.industry,
                "employees": c.employees,
                "revenue_usd": c.revenue_usd,
                "technologies": json.dumps(c.technologies or []),
                "brief": c.brief,
                "status": c.status,
                "drop_reason": c.drop_reason,
                "signal_summary": c.signal_summary,
                "ts": ts,
            })
        return True

    def update_company(self, domain: str, **fields: Any) -> None:
        if not fields:
            return
        fields["updated_at"] = now_iso()
        sets = ", ".join(f"{k} = :{k}" for k in fields)
        params = dict(fields)
        params["domain"] = domain
        with self.engine.begin() as conn:
            conn.execute(
                text(f"UPDATE companies SET {sets} WHERE domain = :domain"), params
            )

    def companies_by_status(self, brief: str, status: str) -> list[Company]:
        with self.engine.connect() as conn:
            rows = conn.execute(text(
                "SELECT * FROM companies WHERE brief = :b AND status = :s "
                "ORDER BY sourced_at DESC"
            ), {"b": brief, "s": status}).fetchall()
        return [_company_from_row(r) for r in rows]

    def get_company(self, domain: str) -> Optional[Company]:
        with self.engine.connect() as conn:
            r = conn.execute(
                text("SELECT * FROM companies WHERE domain = :d"), {"d": domain}
            ).first()
        return _company_from_row(r) if r else None

    # -- contacts -------------------------------------------------------------

    def insert_contact(self, c: Contact) -> bool:
        """Insert an ENRICHED contact. Returns False if the email already
        exists or is suppressed (single-touch dedup)."""
        if self.contact_exists(c.email) or self.is_suppressed(c.email):
            return False
        ts = now_iso()
        with self.engine.begin() as conn:
            conn.execute(text(
                """
                INSERT INTO contacts
                  (email, company_domain, first_name, last_name, title, seniority,
                   linkedin, brief, cell, first_line, subject, body, status,
                   enriched_at, updated_at)
                VALUES
                  (:email, :company_domain, :first_name, :last_name, :title, :seniority,
                   :linkedin, :brief, :cell, :first_line, :subject, :body, :status,
                   :ts, :ts)
                """
            ), {
                "email": c.email,
                "company_domain": c.company_domain,
                "first_name": c.first_name,
                "last_name": c.last_name,
                "title": c.title,
                "seniority": c.seniority,
                "linkedin": c.linkedin,
                "brief": c.brief,
                "cell": c.cell,
                "first_line": c.first_line,
                "subject": c.subject,
                "body": c.body,
                "status": c.status,
                "ts": ts,
            })
        return True

    def update_contact(self, email: str, **fields: Any) -> None:
        if not fields:
            return
        fields["updated_at"] = now_iso()
        sets = ", ".join(f"{k} = :{k}" for k in fields)
        params = dict(fields)
        params["email"] = email
        with self.engine.begin() as conn:
            conn.execute(
                text(f"UPDATE contacts SET {sets} WHERE email = :email"), params
            )

    def contacts_by_status(self, brief: str, status: str,
                           limit: Optional[int] = None) -> list[Contact]:
        sql = ("SELECT * FROM contacts WHERE brief = :b AND status = :s "
               "ORDER BY enriched_at DESC")
        params: dict[str, Any] = {"b": brief, "s": status}
        if limit is not None:
            sql += " LIMIT :lim"
            params["lim"] = limit
        with self.engine.connect() as conn:
            rows = conn.execute(text(sql), params).fetchall()
        return [_contact_from_row(r) for r in rows]

    def contacts_for_company(self, domain: str) -> list[Contact]:
        with self.engine.connect() as conn:
            rows = conn.execute(text(
                "SELECT * FROM contacts WHERE company_domain = :d"), {"d": domain}
            ).fetchall()
        return [_contact_from_row(r) for r in rows]

    def get_contact(self, email: str) -> Optional[Contact]:
        with self.engine.connect() as conn:
            r = conn.execute(
                text("SELECT * FROM contacts WHERE email = :e"), {"e": email}
            ).first()
        return _contact_from_row(r) if r else None

    # -- suppression ----------------------------------------------------------

    def add_suppression(self, key: str, scope: str, reason: str) -> None:
        with self.engine.begin() as conn:
            # Upsert-ish: ignore if already present.
            exists = conn.execute(
                text("SELECT 1 FROM suppression WHERE key = :k"), {"k": key}
            ).first()
            if exists:
                return
            conn.execute(text(
                "INSERT INTO suppression (key, scope, reason, added_at) "
                "VALUES (:k, :s, :r, :t)"
            ), {"k": key, "s": scope, "r": reason, "t": now_iso()})

    def all_suppression_keys(self) -> list[str]:
        with self.engine.connect() as conn:
            rows = conn.execute(text("SELECT key FROM suppression")).fetchall()
        return [r[0] for r in rows]

    # -- events ---------------------------------------------------------------

    def add_event(self, email: Optional[str], type_: str,
                  payload: Optional[dict] = None) -> None:
        with self.engine.begin() as conn:
            conn.execute(text(
                "INSERT INTO events (email, type, payload, at) "
                "VALUES (:e, :t, :p, :at)"
            ), {
                "e": email,
                "t": type_,
                "p": json.dumps(payload or {}),
                "at": now_iso(),
            })

    # -- runs -----------------------------------------------------------------

    def start_run(self, run_id: str, brief: str, stage: str) -> None:
        with self.engine.begin() as conn:
            conn.execute(text(
                "INSERT INTO runs (run_id, brief, stage, status, counts, started_at) "
                "VALUES (:id, :b, :s, 'started', :c, :t)"
            ), {"id": run_id, "b": brief, "s": stage, "c": json.dumps({}),
                "t": now_iso()})

    def finish_run(self, run_id: str, status: str, counts: dict) -> None:
        with self.engine.begin() as conn:
            conn.execute(text(
                "UPDATE runs SET status = :st, counts = :c, finished_at = :t "
                "WHERE run_id = :id"
            ), {"st": status, "c": json.dumps(counts), "t": now_iso(),
                "id": run_id})

    def last_run(self, brief: str) -> Optional[dict]:
        with self.engine.connect() as conn:
            r = conn.execute(text(
                "SELECT * FROM runs WHERE brief = :b "
                "ORDER BY started_at DESC LIMIT 1"
            ), {"b": brief}).first()
        return dict(r._mapping) if r else None

    def runs_for_brief(self, brief: str) -> list[dict]:
        with self.engine.connect() as conn:
            rows = conn.execute(text(
                "SELECT * FROM runs WHERE brief = :b ORDER BY started_at"
            ), {"b": brief}).fetchall()
        return [dict(r._mapping) for r in rows]

    # -- aggregates / status --------------------------------------------------

    def count_companies_by_status(self, brief: str) -> dict[str, int]:
        with self.engine.connect() as conn:
            rows = conn.execute(text(
                "SELECT status, COUNT(*) AS n FROM companies WHERE brief = :b "
                "GROUP BY status"
            ), {"b": brief}).fetchall()
        return {r._mapping["status"]: r._mapping["n"] for r in rows}

    def count_contacts_by_status(self, brief: str) -> dict[str, int]:
        with self.engine.connect() as conn:
            rows = conn.execute(text(
                "SELECT status, COUNT(*) AS n FROM contacts WHERE brief = :b "
                "GROUP BY status"
            ), {"b": brief}).fetchall()
        return {r._mapping["status"]: r._mapping["n"] for r in rows}

    def reservoir_count(self, brief: str) -> int:
        """The reservoir is QUEUED contacts for the brief."""
        return self.count_contacts_by_status(brief).get("QUEUED", 0)

    def total_cost(self, brief: str) -> float:
        """Sum cost_usd across all run records for the brief."""
        total = 0.0
        for run in self.runs_for_brief(brief):
            counts = run.get("counts")
            if counts:
                try:
                    total += float(json.loads(counts).get("cost_usd", 0.0))
                except (ValueError, TypeError):
                    pass
        return total

    def briefs_in_db(self) -> list[str]:
        with self.engine.connect() as conn:
            rows = conn.execute(
                text("SELECT DISTINCT brief FROM companies")
            ).fetchall()
        return [r[0] for r in rows]
